version: '3'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      - NODE_ENV=development
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_USER=postgres
      - POSTGRES_DB=mydatabase
    depends_on:
      - db
    command: npm run dev
  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_USER=postgres
      - POSTGRES_DB=mydatabase
    volumes:
      - db_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
volumes:
  db_data:
